---
title: "gvmap 1000 samples"
author: "Dai Yuting"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```


``` {r echo = TRUE, eval = FALSE}

library(configr)
library(dendextend)
library(matrixStats)
library(easySVG)
library(rsvg)
library(stringr)
library(gvmap)

# ????????????
output_dir <- getwd()

# ????????????????????????
sample_info <- read.table("/home/dyt/projects/ball/analysis/metarnaseq/comGroup/ball.sampleinfo.txt", sep = "\t", header = T, comment.char = "!")

# ??????????????????
mutation_info <- read.table("/home/dyt/projects/ball/analysis/metarnaseq/comGroup/mutation_matrix.txt", sep = "\t", header = T, comment.char = "!")

# ???????????????????????????????????????????????????????????????????????????????????????????????????????????????
exp_data <- read.table("/home/dyt/projects/ball/analysis/metarnaseq/comGroup/filter_exp_mat.txt", header = T, sep = "\t")

# ???1285????????????????????????
sel_sample <- data.frame(sample = colnames(exp_data))

exp_data <- as.matrix(exp_data)
gene_var <- rowVars(exp_data)

gene_var_data <- data.frame(index = c(1:length(gene_var)), var = gene_var)

exp_data_sort <- exp_data[gene_var_data$index[order(gene_var_data$var, decreasing = T)], ]
sig_exp_data <- head(exp_data_sort, floor(length(gene_var)*0.1))

# ??????heatmap data
heatmap_data <- list(heatmap_1 = sig_exp_data)

legend_data_1 <- merge(sel_sample, sample_info, by.x = "sample", by.y = "nid", sort = F, all.x = T)
row.names(legend_data_1) <- legend_data_1$sample

# ?????????????????????
mun_tag <- rep(0, length(mutation_info))
for (i in 1:length(mutation_info)) {
  mun_tag[i] <- length(which(mutation_info[, i] == "0"))
}
table(mun_tag)
plot_mut_mat <- mutation_info[, (mun_tag < 1285)]

mut_merge <- merge(sel_sample, plot_mut_mat, by.x = "sample", by.y = 0, sort = F, all.x = T)

# ??????legend data
legend_data <- cbind(legend_data_1, mut_merge)

# config ??????
config_file <- "/home/dyt/projects/ball/analysis/metarnaseq/comGroup/config.allsample.yaml"

# ?????????????????????
output_svg_name <- paste0(output_dir, "/out_all_sample_kmer_svg")

# ??????gvmap
gvmap(legend_data = legend_data,
      heatmap_data = heatmap_data,
      config_file = config_file,
      output_svg_name = output_svg_name,
      stroke_width = 0.1,
      dend_stroke_width = 1,
      frame_stroke_width = 1,
      sample_span = 2,
      sample_font_size = 1,
      convert_jpg = T)



```
